apiVersion: v1
kind: Secret
metadata:
  name: {{ include "harvey-backend.secretName" . }}
  labels:
    {{- include "harvey-backend.labels" . | nindent 4 }}
type: Opaque
data:
  database_url: {{ .Values.secrets.database_url | b64enc | quote }}
  redis_url: {{ .Values.secrets.redis_url | b64enc | quote }}
  qdrant_url: {{ .Values.secrets.qdrant_url | b64enc | quote }}
  openai_api_key: {{ .Values.secrets.openai_api_key | b64enc | quote }}
  anthropic_api_key: {{ .Values.secrets.anthropic_api_key | b64enc | quote }}
  google_api_key: {{ .Values.secrets.google_api_key | b64enc | quote }}
  jwt_secret: {{ .Values.secrets.jwt_secret | b64enc | quote }}
